<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 17 Lecture 6 Exercises | PS9591: Regressions and Causal Inference</title>
<meta name="author" content="Dr. Sebastián Vallejo Vera | Western University">
<meta name="description" content="This tutorial was created by John Santos (with minor adaptations from me).  17.1 How to (nicely) display model results If we want to display models in a more aesthetically-pleasing format than...">
<meta name="generator" content="bookdown 0.42 with bs4_book()">
<meta property="og:title" content="Chapter 17 Lecture 6 Exercises | PS9591: Regressions and Causal Inference">
<meta property="og:type" content="book">
<meta property="og:description" content="This tutorial was created by John Santos (with minor adaptations from me).  17.1 How to (nicely) display model results If we want to display models in a more aesthetically-pleasing format than...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 17 Lecture 6 Exercises | PS9591: Regressions and Causal Inference">
<meta name="twitter:description" content="This tutorial was created by John Santos (with minor adaptations from me).  17.1 How to (nicely) display model results If we want to display models in a more aesthetically-pleasing format than...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">PS9591: Regressions and Causal Inference</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">“Regressions and Causal Inference”</a></li>
<li><a class="" href="lecture-1-what-is-causal-inference.html"><span class="header-section-number">1</span> Lecture 1: What is Causal Inference?</a></li>
<li><a class="" href="tutorial-1-getting-started-with-r-rstudio-and-rmarkdown.html"><span class="header-section-number">2</span> Tutorial 1: Getting Started with R, RStudio and RMarkdown</a></li>
<li><a class="" href="lecture-2-introduction-to-causal-inference.html"><span class="header-section-number">3</span> Lecture 2: Introduction to Causal Inference</a></li>
<li><a class="" href="tutorial-2-key-concepts.html"><span class="header-section-number">4</span> Tutorial 2: Key Concepts</a></li>
<li><a class="" href="lecture-2-exercises.html"><span class="header-section-number">5</span> Lecture 2 Exercises</a></li>
<li><a class="" href="lecture-3-core-concepts-of-experimental-design.html"><span class="header-section-number">6</span> Lecture 3: Core Concepts of Experimental Design</a></li>
<li><a class="" href="tutorial-3-more-key-concepts.html"><span class="header-section-number">7</span> Tutorial 3: More Key Concepts</a></li>
<li><a class="" href="lecture-3-exercises.html"><span class="header-section-number">8</span> Lecture 3 Exercises</a></li>
<li><a class="" href="lecture-4-the-simple-regression-model-i.html"><span class="header-section-number">9</span> Lecture 4: The Simple Regression Model I</a></li>
<li><a class="" href="tutorial-4-the-simple-regression-model-i.html"><span class="header-section-number">10</span> Tutorial 4: The Simple Regression Model I</a></li>
<li><a class="" href="lecture-4-exercises.html"><span class="header-section-number">11</span> Lecture 4 Exercises</a></li>
<li><a class="" href="lecture-5-the-simple-regression-model-ii.html"><span class="header-section-number">12</span> Lecture 5: The Simple Regression Model II</a></li>
<li><a class="" href="tutorial-5-the-simple-regression-model-ii.html"><span class="header-section-number">13</span> Tutorial 5: The Simple Regression Model II</a></li>
<li><a class="" href="homework-1-practice.html"><span class="header-section-number">14</span> Homework 1 Practice:</a></li>
<li><a class="" href="lecture-6-the-multiple-regression-model-i.html"><span class="header-section-number">15</span> Lecture 6: The Multiple Regression Model I</a></li>
<li><a class="" href="tutorial-6-regression-analysis-and-interpretation.html"><span class="header-section-number">16</span> Tutorial 6: Regression Analysis and Interpretation</a></li>
<li><a class="active" href="lecture-6-exercises.html"><span class="header-section-number">17</span> Lecture 6 Exercises</a></li>
<li><a class="" href="lecture-7-the-multiple-regression-model-ii.html"><span class="header-section-number">18</span> Lecture 7: The Multiple Regression Model II</a></li>
<li><a class="" href="tutorial-7-multiple-regression-analysis.html"><span class="header-section-number">19</span> Tutorial 7: Multiple Regression Analysis</a></li>
<li><a class="" href="lecture-8-the-multiple-regression-model-interpretation.html"><span class="header-section-number">20</span> Lecture 8: The Multiple Regression Model: Interpretation</a></li>
<li><a class="" href="lecture-9-exercises.html"><span class="header-section-number">21</span> Lecture 9 Exercises</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/svallejovera/regression_ci">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="lecture-6-exercises" class="section level1" number="17">
<h1>
<span class="header-section-number">17</span> Lecture 6 Exercises<a class="anchor" aria-label="anchor" href="#lecture-6-exercises"><i class="fas fa-link"></i></a>
</h1>
<p><em>This tutorial was created by <a href="https://jb-santos.github.io/">John Santos</a></em> (with minor adaptations from me).</p>
<div id="how-to-nicely-display-model-results" class="section level2" number="17.1">
<h2>
<span class="header-section-number">17.1</span> How to (nicely) display model results<a class="anchor" aria-label="anchor" href="#how-to-nicely-display-model-results"><i class="fas fa-link"></i></a>
</h2>
<p>If we want to display models in a more aesthetically-pleasing format than with the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> command, we have a few options.</p>
<p>Let’s start by running some models.</p>
<div class="sourceCode" id="cb360"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://justinmshea.github.io/wooldridge/">wooldridge</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"wage1"</span><span class="op">)</span></span>
<span><span class="va">wage_mod1</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span>, data<span class="op">=</span><span class="va">wage1</span><span class="op">)</span></span>
<span><span class="va">wage_mod1a</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">wage</span><span class="op">*</span><span class="fl">100</span><span class="op">)</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span>, data<span class="op">=</span><span class="va">wage1</span><span class="op">)</span></span>
<span><span class="va">wage_mod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span>, data<span class="op">=</span><span class="va">wage1</span><span class="op">)</span></span></code></pre></div>
<div id="the-boring-ugly-way-base-r" class="section level3" number="17.1.1">
<h3>
<span class="header-section-number">17.1.1</span> The boring, ugly way (Base <code>R</code>)<a class="anchor" aria-label="anchor" href="#the-boring-ugly-way-base-r"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb361"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wage_mod1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ educ + exper, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5532 -1.9801 -0.7071  1.2030 15.8370 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.39054    0.76657  -4.423 1.18e-05 ***
## educ         0.64427    0.05381  11.974  &lt; 2e-16 ***
## exper        0.07010    0.01098   6.385 3.78e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.257 on 523 degrees of freedom
## Multiple R-squared:  0.2252, Adjusted R-squared:  0.2222 
## F-statistic: 75.99 on 2 and 523 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb363"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wage_mod1a</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = I(wage * 100) ~ educ + exper, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -555.32 -198.01  -70.71  120.30 1583.70 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -339.054     76.657  -4.423 1.18e-05 ***
## educ          64.427      5.381  11.974  &lt; 2e-16 ***
## exper          7.010      1.098   6.385 3.78e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 325.7 on 523 degrees of freedom
## Multiple R-squared:  0.2252, Adjusted R-squared:  0.2222 
## F-statistic: 75.99 on 2 and 523 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb365"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wage_mod2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ educ, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.3396 -2.1501 -0.9674  1.1921 16.6085 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.90485    0.68497  -1.321    0.187    
## educ         0.54136    0.05325  10.167   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.378 on 524 degrees of freedom
## Multiple R-squared:  0.1648, Adjusted R-squared:  0.1632 
## F-statistic: 103.4 on 1 and 524 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="stargazer" class="section level3" number="17.1.2">
<h3>
<span class="header-section-number">17.1.2</span> <code>{stargazer}</code><a class="anchor" aria-label="anchor" href="#stargazer"><i class="fas fa-link"></i></a>
</h3>
<p>The easiest is to use the <code>{stargazer}</code> package and its eponymously-named function. This package is easy enough, flexible enough, but, unfortunately, no longer maintained.</p>
<div class="sourceCode" id="cb367"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">stargazer</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Please cite as:</code></pre>
<pre><code>##  Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
<pre><code>##  R package version 5.2.3. https://CRAN.R-project.org/package=stargazer</code></pre>
<div class="sourceCode" id="cb371"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/stargazer/man/stargazer.html">stargazer</a></span><span class="op">(</span><span class="va">wage_mod1</span>, <span class="va">wage_mod1a</span>, <span class="va">wage_mod2</span>,</span>
<span>          title <span class="op">=</span> <span class="st">"Modeling wage versus education and experience"</span>,</span>
<span>          type <span class="op">=</span> <span class="st">"text"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Modeling wage versus education and experience
## ============================================================================================
##                                               Dependent variable:                           
##                     ------------------------------------------------------------------------
##                              wage                I(wage * 100)                wage          
##                               (1)                     (2)                     (3)           
## --------------------------------------------------------------------------------------------
## educ                       0.644***                64.427***                0.541***        
##                             (0.054)                 (5.381)                 (0.053)         
##                                                                                             
## exper                      0.070***                7.010***                                 
##                             (0.011)                 (1.098)                                 
##                                                                                             
## Constant                   -3.391***              -339.054***                -0.905         
##                             (0.767)                (76.657)                 (0.685)         
##                                                                                             
## --------------------------------------------------------------------------------------------
## Observations                  526                     526                     526           
## R2                           0.225                   0.225                   0.165          
## Adjusted R2                  0.222                   0.222                   0.163          
## Residual Std. Error    3.257 (df = 523)       325.704 (df = 523)        3.378 (df = 524)    
## F Statistic         75.990*** (df = 2; 523) 75.990*** (df = 2; 523) 103.363*** (df = 1; 524)
## ============================================================================================
## Note:                                                            *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>For <code>{stargazer}</code>, you want to set the <code>type=</code> option to “text” while you work in RStudio, but change it to “html” or “latex” when you output your final document (respectively, as an HTML file or .tex file).</p>
</div>
<div id="modelsummary" class="section level3" number="17.1.3">
<h3>
<span class="header-section-number">17.1.3</span> <code>{modelsummary}</code><a class="anchor" aria-label="anchor" href="#modelsummary"><i class="fas fa-link"></i></a>
</h3>
<p>We can also use the package <a href="https://modelsummary.com">modelsummary</a> and its function <code><a href="https://modelsummary.com/man/msummary.html">msummary()</a></code>. This package is a little more involved, but produces a more flexible output, works with a wider variety of models, and is actively maintained.</p>
<div class="sourceCode" id="cb373"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://modelsummary.com">modelsummary</a></span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Attaching package: 'modelsummary'</code></pre>
<pre><code>## The following object is masked from 'package:psych':
## 
##     SD</code></pre>
<div class="sourceCode" id="cb376"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://modelsummary.com/man/msummary.html">msummary</a></span><span class="op">(</span>models <span class="op">=</span> <span class="fu"><a href="https://modelsummary.com/man/dvnames.html">dvnames</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">wage_mod1</span>, <span class="va">wage_mod1a</span>, <span class="va">wage_mod2</span><span class="op">)</span><span class="op">)</span>,</span>
<span>         statistic <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"std.error"</span>, <span class="st">"p.value"</span><span class="op">)</span>,</span>
<span>         stars <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>         title <span class="op">=</span> <span class="st">"Modeling wage versus education and experience"</span>,</span>
<span>         notes <span class="op">=</span> <span class="st">"Cell entries are parameter estimates, standard errors, and p values"</span><span class="op">)</span></span></code></pre></div>
<!-- preamble start -->

    <script>

      function styleCell_mbf808wsusn0xxtp1og0(i, j, css_id) {
          var table = document.getElementById("tinytable_mbf808wsusn0xxtp1og0");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_mbf808wsusn0xxtp1og0');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_mbf808wsusn0xxtp1og0(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_mbf808wsusn0xxtp1og0");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 17, j: 1 }, { i: 17, j: 2 }, { i: 17, j: 3 },  ], css_id: 'tinytable_css_quqrwyynbg9ujnp6a83l',}, 
          { positions: [ { i: 9, j: 1 }, { i: 9, j: 2 }, { i: 9, j: 3 },  ], css_id: 'tinytable_css_9orn8lgxsqiky2sakikk',}, 
          { positions: [ { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 4, j: 2 }, { i: 6, j: 1 }, { i: 11, j: 1 }, { i: 12, j: 1 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 15, j: 1 }, { i: 16, j: 1 }, { i: 12, j: 2 }, { i: 5, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 3, j: 2 }, { i: 12, j: 3 }, { i: 10, j: 1 }, { i: 6, j: 2 }, { i: 7, j: 2 }, { i: 8, j: 2 }, { i: 4, j: 3 }, { i: 10, j: 2 }, { i: 11, j: 2 }, { i: 7, j: 3 }, { i: 13, j: 2 }, { i: 14, j: 2 }, { i: 15, j: 2 }, { i: 16, j: 2 }, { i: 3, j: 3 }, { i: 5, j: 2 }, { i: 1, j: 3 }, { i: 2, j: 3 }, { i: 11, j: 3 }, { i: 8, j: 3 }, { i: 5, j: 3 }, { i: 6, j: 3 }, { i: 15, j: 3 }, { i: 16, j: 3 }, { i: 13, j: 3 }, { i: 10, j: 3 }, { i: 14, j: 3 },  ], css_id: 'tinytable_css_hg3p77cvqalquh52fefi',}, 
          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 }, { i: 0, j: 3 },  ], css_id: 'tinytable_css_jk89p7iqkmpl6n2vt99o',}, 
          { positions: [ { i: 17, j: 0 },  ], css_id: 'tinytable_css_95pfnfn5yj1y709loaxs',}, 
          { positions: [ { i: 9, j: 0 },  ], css_id: 'tinytable_css_8tagmyepx5d03adiqp55',}, 
          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 13, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 12, j: 0 }, { i: 14, j: 0 }, { i: 15, j: 0 }, { i: 16, j: 0 },  ], css_id: 'tinytable_css_ign6q4x300lz9r7bkwxp',}, 
          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_58u9f5fkrjlae315w9ys',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_mbf808wsusn0xxtp1og0(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script><style>
      /* tinytable css entries after */
      .table td.tinytable_css_quqrwyynbg9ujnp6a83l, .table th.tinytable_css_quqrwyynbg9ujnp6a83l { text-align: center; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_9orn8lgxsqiky2sakikk, .table th.tinytable_css_9orn8lgxsqiky2sakikk { text-align: center; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_hg3p77cvqalquh52fefi, .table th.tinytable_css_hg3p77cvqalquh52fefi { text-align: center; }
      .table td.tinytable_css_jk89p7iqkmpl6n2vt99o, .table th.tinytable_css_jk89p7iqkmpl6n2vt99o { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_95pfnfn5yj1y709loaxs, .table th.tinytable_css_95pfnfn5yj1y709loaxs { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_8tagmyepx5d03adiqp55, .table th.tinytable_css_8tagmyepx5d03adiqp55 { text-align: left; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_ign6q4x300lz9r7bkwxp, .table th.tinytable_css_ign6q4x300lz9r7bkwxp { text-align: left; }
      .table td.tinytable_css_58u9f5fkrjlae315w9ys, .table th.tinytable_css_58u9f5fkrjlae315w9ys { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
    </style>
<div class="container">
      <div class="inline-table"><table class="table table-borderless" id="tinytable_mbf808wsusn0xxtp1og0" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
<thead>
<caption>Modeling wage versus education and experience</caption>
              <tr>
<th scope="col"> </th>
                <th scope="col">wage</th>
                <th scope="col">I(wage * 100)</th>
                <th scope="col">wage </th>
              </tr>
</thead>
<tfoot>
<tr><td colspan="4">+ p </td></tr>
<tr><td colspan="4">Cell entries are parameter estimates, standard errors, and p values</td></tr>
</tfoot>
<tbody>
<tr>
<td>(Intercept)</td>
                  <td>-3.391***</td>
                  <td>-339.054***</td>
                  <td>-0.905</td>
                </tr>
<tr>
<td></td>
                  <td>(0.767)</td>
                  <td>(76.657)</td>
                  <td>(0.685)</td>
                </tr>
<tr>
<td></td>
                  <td>(
                  </td>
<td>(
                  </td>
<td>(0.187)</td>
                </tr>
<tr>
<td>educ</td>
                  <td>0.644***</td>
                  <td>64.427***</td>
                  <td>0.541***</td>
                </tr>
<tr>
<td></td>
                  <td>(0.054)</td>
                  <td>(5.381)</td>
                  <td>(0.053)</td>
                </tr>
<tr>
<td></td>
                  <td>(
                  </td>
<td>(
                  </td>
<td>(
                </td>
</tr>
<tr>
<td>exper</td>
                  <td>0.070***</td>
                  <td>7.010***</td>
                  <td></td>
                </tr>
<tr>
<td></td>
                  <td>(0.011)</td>
                  <td>(1.098)</td>
                  <td></td>
                </tr>
<tr>
<td></td>
                  <td>(
                  </td>
<td>(
                  </td>
<td></td>
                </tr>
<tr>
<td>Num.Obs.</td>
                  <td>526</td>
                  <td>526</td>
                  <td>526</td>
                </tr>
<tr>
<td>R2</td>
                  <td>0.225</td>
                  <td>0.225</td>
                  <td>0.165</td>
                </tr>
<tr>
<td>R2 Adj.</td>
                  <td>0.222</td>
                  <td>0.222</td>
                  <td>0.163</td>
                </tr>
<tr>
<td>AIC</td>
                  <td>2739.9</td>
                  <td>7584.6</td>
                  <td>2777.4</td>
                </tr>
<tr>
<td>BIC</td>
                  <td>2757.0</td>
                  <td>7601.6</td>
                  <td>2790.2</td>
                </tr>
<tr>
<td>Log.Lik.</td>
                  <td>-1365.969</td>
                  <td>-3788.288</td>
                  <td>-1385.712</td>
                </tr>
<tr>
<td>F</td>
                  <td>75.990</td>
                  <td>75.990</td>
                  <td>103.363</td>
                </tr>
<tr>
<td>RMSE</td>
                  <td>3.25</td>
                  <td>324.77</td>
                  <td>3.37</td>
                </tr>
</tbody>
</table></div>
</div>
<!-- hack to avoid NA insertion in last line -->
<hr>
</div>
</div>
<div id="functional-form" class="section level2" number="17.2">
<h2>
<span class="header-section-number">17.2</span> Functional form<a class="anchor" aria-label="anchor" href="#functional-form"><i class="fas fa-link"></i></a>
</h2>
<div id="feelings-towards-the-lpc-quadratics" class="section level3" number="17.2.1">
<h3>
<span class="header-section-number">17.2.1</span> Feelings towards the LPC (quadratics)<a class="anchor" aria-label="anchor" href="#feelings-towards-the-lpc-quadratics"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Quadratics</strong> on the right-hand-side (<em>RHS</em>) of a regression equation are useful for capturing non-linear relationships, especially when that relationship is <em>non-monotonic</em>.</p>
<p>When a function is <em>non-monotonic</em>, it means that it switches direction (either positive to negative or negative to positive).</p>
<p>We’ll demonstrate this by modelling feelings towards the Liberal Party of Canada and market liberalism.</p>
<div class="sourceCode" id="cb377"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span><span class="op">(</span><span class="st">"Sample_data/ces.rda"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">marketlib</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##    0.00    6.00    9.00    8.59   11.00   16.00   32684</code></pre>
<div class="sourceCode" id="cb379"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">feel_lib</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##    0.00   16.00   54.00   48.34   77.00  100.00    2640</code></pre>
<div class="sourceCode" id="cb381"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ces</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">feel_lib</span>, y <span class="op">=</span> <span class="va">marketlib</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, </span>
<span>              formula <span class="op">=</span> <span class="st">"y ~ x + I(x^2)"</span>, </span>
<span>              color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-129-1.png" width="672"></div>
<div class="sourceCode" id="cb383"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">feel1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">feel_lib</span> <span class="op">~</span> <span class="va">marketlib</span>, data <span class="op">=</span> <span class="va">ces</span><span class="op">)</span></span>
<span><span class="va">feel2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">feel_lib</span> <span class="op">~</span> <span class="va">marketlib</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">marketlib</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ces</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/stargazer/man/stargazer.html">stargazer</a></span><span class="op">(</span><span class="va">feel1</span>, <span class="va">feel2</span>,</span>
<span>          type <span class="op">=</span> <span class="st">"text"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## =======================================================================
##                                     Dependent variable:                
##                     ---------------------------------------------------
##                                          feel_lib                      
##                                (1)                       (2)           
## -----------------------------------------------------------------------
## marketlib                   -2.802***                   0.654          
##                              (0.130)                   (0.481)         
##                                                                        
## I(marketlib2)                                         -0.216***        
##                                                        (0.029)         
##                                                                        
## Constant                    71.472***                 60.439***        
##                              (1.203)                   (1.904)         
##                                                                        
## -----------------------------------------------------------------------
## Observations                  4,781                     4,781          
## R2                            0.089                     0.099          
## Adjusted R2                   0.089                     0.099          
## Residual Std. Error    31.808 (df = 4779)        31.628 (df = 4778)    
## F Statistic         466.091*** (df = 1; 4779) 263.454*** (df = 2; 4778)
## =======================================================================
## Note:                                       *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>The effect of X on Y, or of <em>marketlib</em> on <em>feel_lib</em> requires both <span class="math inline">\(\hat{\beta_1}\)</span> and <span class="math inline">\(\hat{\beta_2}\)</span>, as can be seen below.</p>
<p><span class="math display">\[\begin{aligned}
\hat{feellib} &amp;= 60.439 + 0.654marketlib - 0.216marketlib^2 \\
\Delta\hat{feellib} &amp;= 0.654marketlib - 0.216marketlib^2
\end{aligned}\]</span></p>
<p>The above has a convenient approximation of <span class="math inline">\(\Delta{\hat{y}} &amp;= \hat{\beta_1}x + \hat{\beta_2}x^2\)</span>, which is applied as follows:</p>
<p><span class="math display">\[\begin{aligned}
\Delta{\hat{y}} &amp;= \hat{\beta_1}x + \hat{\beta_2}x^2  \\
\Delta{\hat{y}} &amp;\approx [\hat{\beta_1} + (2 \times \hat{\beta_2}x)] \Delta{x}  \\
\Delta\hat{feellib} &amp;\approx [0.654 - (2 \times 0.216marketlib)] \Delta{marketlib}  \\
\Delta\hat{feellib} &amp;\approx [0.654 - 0.432marketlib] \Delta{marketlib}  \\
\Delta{marketlib} &amp;= 1  &amp;&amp; \text{(because we're looking at a one-unit change in marketlib)}  \\
\Delta\hat{feellib} &amp;\approx [0.654 - 0.432marketlib]
\end{aligned}\]</span></p>
<div id="calculating-the-turning-point-of-a-quadratic" class="section level4" number="17.2.1.1">
<h4>
<span class="header-section-number">17.2.1.1</span> Calculating the turning point of a quadratic<a class="anchor" aria-label="anchor" href="#calculating-the-turning-point-of-a-quadratic"><i class="fas fa-link"></i></a>
</h4>
<p>The point (at least theoretically) at which a quadratic function changes direction is called the <strong>turning point</strong>, or the <strong>inflection point</strong>, or a functional <strong>minimum</strong>/<strong>maximum</strong>. It is often represented as <span class="math inline">\(x\star\)</span>.</p>
<p>Another way to think about this is the point at which the rate of change of Y across values of X equals 0, or more formally <span class="math inline">\(\Delta{\hat{y}} = 0\)</span>.</p>
<p>For quadratic equations of <span class="math inline">\(\hat{y} = \hat\beta_0 + \hat\beta_1x + \hat\beta_2x^2\)</span> this point can be calculated with the formula <span class="math inline">\(x\star = -\hat\beta_1 / 2\hat\beta_2\)</span>.</p>
<p>For the example above, this point is
<span class="math display">\[\begin{aligned}
x\star &amp;= -\hat\beta_1 / 2\hat\beta_2  \\
x\star &amp;= -0.654 / (2 \times 0.216)  \\
x\star &amp;= -0.654 / 0.432  \\
x\star &amp;= -1.513889
\end{aligned}\]</span></p>
<p>So, the turning point at which a one-unit change in <em>marketlib</em> causes feelings towards the LPC to change direction is -1.5. This is outside of the actual range of the <em>marketlib</em> variable, so it is of no relevance to us (hence why the turning point is sometimes only theoretical).</p>
<p>You’ll encounter this later in the course, so don’t worry about this too much at this point.</p>
<hr>
</div>
</div>
<div id="occupational-prestige-logarithms" class="section level3" number="17.2.2">
<h3>
<span class="header-section-number">17.2.2</span> Occupational prestige (logarithms)<a class="anchor" aria-label="anchor" href="#occupational-prestige-logarithms"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Logarithms</strong> are useful on both the right- (predictor) and left-hand-side (outcome) of regression equations.</p>
<p>The log of <span class="math inline">\(X\)</span> is useful when that predictor has large effects on <span class="math inline">\(Y\)</span> at low levels of <span class="math inline">\(X\)</span> but smaller effects at higher levels of <span class="math inline">\(X\)</span>.</p>
<p>It can also be useful in the converse situation.</p>
<div class="sourceCode" id="cb385"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">carData</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    education          income          women           prestige         census    
##  Min.   : 6.380   Min.   :  611   Min.   : 0.000   Min.   :14.80   Min.   :1113  
##  1st Qu.: 8.445   1st Qu.: 4106   1st Qu.: 3.592   1st Qu.:35.23   1st Qu.:3120  
##  Median :10.540   Median : 5930   Median :13.600   Median :43.60   Median :5135  
##  Mean   :10.738   Mean   : 6798   Mean   :28.979   Mean   :46.83   Mean   :5402  
##  3rd Qu.:12.648   3rd Qu.: 8187   3rd Qu.:52.203   3rd Qu.:59.27   3rd Qu.:8312  
##  Max.   :15.970   Max.   :25879   Max.   :97.510   Max.   :87.20   Max.   :9517  
##    type   
##  bc  :44  
##  prof:31  
##  wc  :23  
##  NA's: 4  
##           
## </code></pre>
<div class="sourceCode" id="cb387"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">income</span>, y <span class="op">=</span> <span class="va">prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"prestige ~ income"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-130-1.png" width="672"></div>
<div class="sourceCode" id="cb389"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">prest1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">prestige</span> <span class="op">~</span> <span class="va">income</span>, data <span class="op">=</span> <span class="va">Prestige</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">prest1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prestige ~ income, data = Prestige)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.007  -8.378  -2.378   8.432  32.084 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.714e+01  2.268e+00   11.97   &lt;2e-16 ***
## income      2.897e-03  2.833e-04   10.22   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 12.09 on 100 degrees of freedom
## Multiple R-squared:  0.5111, Adjusted R-squared:  0.5062 
## F-statistic: 104.5 on 1 and 100 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><span class="math display">\[\hat{prestige} = 2.714 + 0.002897income\]</span></p>
<p>For every increase in income of $1, prestige increases by about 0.002897 points on a scale from 14 to 87 points.</p>
<p>Alternatively, for every increase in $1000, prestige increases by about 2.9 points (0.002897 * 1000 = 2.897).</p>
<p><strong>BUT</strong>…, is the relationship actually linear?</p>
<div class="sourceCode" id="cb391"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">income</span>, y <span class="op">=</span> <span class="va">prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, formula <span class="op">=</span> <span class="st">"y ~ log(x)"</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"prestige ~ income"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-131-1.png" width="672"></div>
<p>It looks like a logarithmic function might work better, so let’s try that.</p>
<p>To make the coefficients easier to interpret, we’ll make a new variable that is a transformation of income, but measured in thousands.</p>
<div class="sourceCode" id="cb393"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Prestige</span><span class="op">$</span><span class="va">income1000</span> <span class="op">&lt;-</span> <span class="va">Prestige</span><span class="op">$</span><span class="va">income</span> <span class="op">/</span> <span class="fl">1000</span></span>
<span><span class="va">prest1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">prestige</span> <span class="op">~</span> <span class="va">income1000</span>, data <span class="op">=</span> <span class="va">Prestige</span><span class="op">)</span></span>
<span><span class="va">prest2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">prestige</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">income1000</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">Prestige</span><span class="op">)</span></span>
<span><span class="va">prest3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">prestige</span><span class="op">)</span> <span class="op">~</span> <span class="va">income1000</span>, data <span class="op">=</span> <span class="va">Prestige</span><span class="op">)</span></span>
<span><span class="va">prest4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">prestige</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">income1000</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">Prestige</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">stargazer</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/stargazer/man/stargazer.html">stargazer</a></span><span class="op">(</span><span class="va">prest1</span>, <span class="va">prest2</span>, <span class="va">prest3</span>, <span class="va">prest4</span>,</span>
<span>          type <span class="op">=</span> <span class="st">"text"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## =========================================================================
##                                           Dependent variable:            
##                                ------------------------------------------
##                                      prestige           log(prestige)    
##                                   (1)        (2)        (3)       (4)    
## -------------------------------------------------------------------------
## income1000                      2.897***             0.062***            
##                                 (0.283)               (0.007)            
##                                                                          
## log(income1000)                           21.556***             0.499*** 
##                                            (1.953)              (0.044)  
##                                                                          
## Constant                       27.141***   9.050**   3.353***   2.901*** 
##                                 (2.268)    (3.611)    (0.055)   (0.081)  
##                                                                          
## -------------------------------------------------------------------------
## Observations                      102        102        102       102    
## R2                               0.511      0.549      0.452     0.566   
## Adjusted R2                      0.506      0.545      0.447     0.562   
## Residual Std. Error (df = 100)   12.090     11.609     0.291     0.259   
## F Statistic (df = 1; 100)      104.537*** 121.810*** 82.642*** 130.520***
## =========================================================================
## Note:                                         *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p><span class="math display">\[\begin{aligned}
\hat{prestige} &amp;= 27.141 + 2.897income   &amp;&amp; \text{(eq 1: level-level)}  \\
\hat{prestige} &amp;= 9.050 + 21.556log(income)   &amp;&amp; \text{(eq 2: level-log)}  \\
\hat{log(prestige)} &amp;= 3.353 + 0.062income   &amp;&amp; \text{(eq 3: log-level)}  \\
\hat{log(prestige)} &amp;= 2.901 + 0.499log(income)   &amp;&amp; \text{(eq 4: log-log)}
\end{aligned}\]</span></p>
<p>Remembering our rules for interpreting models, which are…</p>
<ol style="list-style-type: decimal">
<li>
<strong>level-level</strong> A unit increase in X results in a b unit increase in Y</li>
<li>
<strong>level-log</strong> A percent increase in X results in a (b/100)*unit increase in Y</li>
<li>
<strong>log-level</strong> A unit increase in X results in a 100*b% increase in Y</li>
<li>
<strong>log-log</strong> A percent increase in X results in a b% increase in Y</li>
</ol>
<p>Therefore, the interpretation of each equation is as follows:</p>
<ol style="list-style-type: decimal">
<li>For every increase in income of $1 (thousand), prestige increases by about 2.897 points.</li>
<li>For every 1% increase in income (in thousands), prestige increases by .21556 points (i.e. <span class="math inline">\(\hat\beta_1/100 = 21.556/100 == 0.21556\)</span>).</li>
<li>For every increase in income of $1 (thousand), prestige increases 6.2% (i.e. <span class="math inline">\(100 * \hat\beta_1 = 0.062/100 == 6.2\%\)</span>).</li>
<li>For every 1% increase in income (in thousands), prestige increases by 0.499%.</li>
</ol>
<div class="sourceCode" id="cb395"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">income</span>, y <span class="op">=</span> <span class="va">prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"prestige ~ income"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"prestige ~ log(income)"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">income</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">prestige</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"log(prestige) ~ income"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">Prestige</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">income</span><span class="op">)</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">prestige</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"log(prestige) ~ log(income)"</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rpkgs.datanovia.com/ggpubr/">ggpubr</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rpkgs.datanovia.com/ggpubr/reference/ggarrange.html">ggarrange</a></span><span class="op">(</span><span class="va">p1</span>, <span class="va">p2</span>, <span class="va">p3</span>, <span class="va">p4</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-133-1.png" width="672"></div>
<hr>
</div>
<div id="automobile-performance-logarithms" class="section level3" number="17.2.3">
<h3>
<span class="header-section-number">17.2.3</span> Automobile performance (logarithms)<a class="anchor" aria-label="anchor" href="#automobile-performance-logarithms"><i class="fas fa-link"></i></a>
</h3>
<p>This is another exercise using the the <em>mtcars</em> dataset from the <code>carData</code> package. We’ll model quarter-mile time (<em>qsec</em>) as a function of horsepower (<em>hp</em>).</p>
<div class="sourceCode" id="cb397"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span></span></code></pre></div>
<pre><code>##       mpg             cyl             disp             hp             drat      
##  Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0   Min.   :2.760  
##  1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5   1st Qu.:3.080  
##  Median :19.20   Median :6.000   Median :196.3   Median :123.0   Median :3.695  
##  Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7   Mean   :3.597  
##  3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0   3rd Qu.:3.920  
##  Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0   Max.   :4.930  
##        wt             qsec             vs               am              gear      
##  Min.   :1.513   Min.   :14.50   Min.   :0.0000   Min.   :0.0000   Min.   :3.000  
##  1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:3.000  
##  Median :3.325   Median :17.71   Median :0.0000   Median :0.0000   Median :4.000  
##  Mean   :3.217   Mean   :17.85   Mean   :0.4375   Mean   :0.4062   Mean   :3.688  
##  3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:4.000  
##  Max.   :5.424   Max.   :22.90   Max.   :1.0000   Max.   :1.0000   Max.   :5.000  
##       carb      
##  Min.   :1.000  
##  1st Qu.:2.000  
##  Median :2.000  
##  Mean   :2.812  
##  3rd Qu.:4.000  
##  Max.   :8.000</code></pre>
<div class="sourceCode" id="cb399"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hpqsec1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">qsec</span> <span class="op">~</span> <span class="va">hp</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span>
<span><span class="va">hpqsec2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">qsec</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">hp</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span>
<span><span class="va">hpqsec3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">qsec</span><span class="op">)</span> <span class="op">~</span> <span class="va">hp</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span>
<span><span class="va">hpqsec4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">qsec</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">hp</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">stargazer</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/stargazer/man/stargazer.html">stargazer</a></span><span class="op">(</span><span class="va">hpqsec1</span>, <span class="va">hpqsec2</span>, <span class="va">hpqsec3</span>, <span class="va">hpqsec4</span>,</span>
<span>          type <span class="op">=</span> <span class="st">"text"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## =====================================================================
##                                         Dependent variable:          
##                               ---------------------------------------
##                                      qsec              log(qsec)     
##                                  (1)       (2)       (3)       (4)   
## ---------------------------------------------------------------------
## hp                            -0.018***           -0.001***          
##                                (0.003)            (0.0002)           
##                                                                      
## log(hp)                                 -2.576***           -0.146***
##                                          (0.500)             (0.027) 
##                                                                      
## Constant                      20.556*** 30.422*** 3.032***  3.591*** 
##                                (0.542)   (2.453)   (0.029)   (0.134) 
##                                                                      
## ---------------------------------------------------------------------
## Observations                     32        32        32        32    
## R2                              0.502     0.469     0.530     0.488  
## Adjusted R2                     0.485     0.451     0.515     0.471  
## Residual Std. Error (df = 30)   1.282     1.323     0.069     0.072  
## F Statistic (df = 1; 30)      30.190*** 26.514*** 33.882*** 28.575***
## =====================================================================
## Note:                                     *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<div class="sourceCode" id="cb401"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">hp</span>, y <span class="op">=</span> <span class="va">qsec</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, formula <span class="op">=</span> <span class="va">y</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"qsec ~ hp"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-136-1.png" width="672"></div>
<div class="sourceCode" id="cb403"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">hp</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">qsec</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, formula <span class="op">=</span> <span class="va">y</span> <span class="op">~</span> <span class="va">x</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"log(qsec) ~ hp"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-136-2.png" width="672"></div>
<div class="sourceCode" id="cb404"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">hp</span><span class="op">)</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">qsec</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, formula <span class="op">=</span> <span class="va">y</span> <span class="op">~</span> <span class="va">x</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"log(qsec) ~ log(hp)"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-136-3.png" width="672"></div>
<hr>
</div>
</div>
<div id="practice-exercises-1" class="section level2" number="17.3">
<h2>
<span class="header-section-number">17.3</span> Practice exercises<a class="anchor" aria-label="anchor" href="#practice-exercises-1"><i class="fas fa-link"></i></a>
</h2>
<p>From lecture:</p>
<p>Using the ‘fertil2’ dataset from ‘wooldridge’ on women living in the Republic of Botswana in 1988…</p>
<ol style="list-style-type: decimal">
<li>Estimate the regression equation of the number of children on education, age of the mother, and electricity.</li>
<li>Interpret <span class="math inline">\(\hat{\beta}_0\)</span>, <span class="math inline">\(\hat{\beta}_{education}\)</span>, <span class="math inline">\(\hat{\beta}_{age}\)</span>, and <span class="math inline">\(\hat{\beta}_{electric}\)</span>.</li>
<li>Verify that sample covariance between predicted values and residuals = 0.</li>
<li>Verify that sample covariance between education and residuals = 0.</li>
<li>Re-estimate the regression equation of the number of children on education, age of the mother, and electricity but also include the square of the age of the mother. How do you now interpret the effect of age on the number of children?</li>
</ol>
<p>Using the ‘wage1’ datadest from ‘woolridge’ on US workers in 1976…</p>
<ol start="6" style="list-style-type: decimal">
<li>Estimate the regression equation of the hourly wage (<em>wage</em>) in dollars on education (<em>educ</em>) and experience (<em>exper</em>).</li>
<li>How do the coefficients change when the units of wages are in cents instead of dollars?</li>
<li>Compare the estimated coefficient for education to the one obtained by regressing only the hourly wage on education. Interpret.</li>
</ol>
<p>Additional exercises for tutorial:</p>
<p>There’s an old saying (often attributed to Winston Churchill) that goes, “If you are not a liberal when you are young, you have no heart. If you are not a conservative when you are old, you have no brain.” And, yet there have been activist left-wing groups comprised of seniors, like the Raging Grannies.</p>
<p>Using our sample CES dataset, explore the relationship between Canadians’ support for free market principles (<span class="math inline">\(marketlib\)</span>) and age (<span class="math inline">\(age\)</span>)? Is there is a relationship? If so, is it <em>linear</em>? We’re going to run two regression models. Model 1 will regress <span class="math inline">\(marketlib\)</span> on <span class="math inline">\(age\)</span>, while controlling for <span class="math inline">\(gender\)</span>. Model 2 will be the same as Model 1, except it will also include the quadratic term for <span class="math inline">\(age\)</span> (i.e. <span class="math inline">\(age^2\)</span>).</p>
</div>
<div id="stop-4" class="section level2" number="17.4">
<h2>
<span class="header-section-number">17.4</span> STOP!!<a class="anchor" aria-label="anchor" href="#stop-4"><i class="fas fa-link"></i></a>
</h2>
<p>Before you continue, try solving the exercises on your own. It’s the only way you will learn. Then, come back to this page and see how well you did.</p>
</div>
<div id="continue-4" class="section level2" number="17.5">
<h2>
<span class="header-section-number">17.5</span> Continue<a class="anchor" aria-label="anchor" href="#continue-4"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="lecture-exercises" class="section level2" number="17.6">
<h2>
<span class="header-section-number">17.6</span> Lecture exercises<a class="anchor" aria-label="anchor" href="#lecture-exercises"><i class="fas fa-link"></i></a>
</h2>
<div id="q1.-estimate-the-regression-equation-of-the-number-of-children-on-education-age-of-the-mother-and-electricity." class="section level3" number="17.6.1">
<h3>
<span class="header-section-number">17.6.1</span> Q1. Estimate the regression equation of the number of children on education, age of the mother, and electricity.<a class="anchor" aria-label="anchor" href="#q1.-estimate-the-regression-equation-of-the-number-of-children-on-education-age-of-the-mother-and-electricity."><i class="fas fa-link"></i></a>
</h3>
<p>Before I begin, I’m going to make a data frame that only contains the variables I need and then listiwise delete all NAs. This will make it easier to run the diagnostic tests.</p>
<div class="sourceCode" id="cb405"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://justinmshea.github.io/wooldridge/">wooldridge</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"fertil2"</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="va">fertil2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">children</span>, <span class="va">educ</span>, <span class="va">age</span>, <span class="va">electric</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## select: dropped 23 variables (mnthborn, yearborn, radio, tv, bicycle, …)</code></pre>
<p>Our population model is:</p>
<p><span class="math display">\[children = \beta_0 + \beta_1educ + \beta_2age + \beta_3electric + u\]</span></p>
<div class="sourceCode" id="cb407"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://justinmshea.github.io/wooldridge/">wooldridge</a></span><span class="op">)</span></span>
<span><span class="va">fertil2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/get.html">get</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">'fertil2'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">fmod1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">children</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">electric</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = children ~ educ + age + electric, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.6019 -0.6814 -0.0619  0.7476  7.1061 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.071091   0.094741 -21.861  &lt; 2e-16 ***
## educ        -0.078751   0.006319 -12.462  &lt; 2e-16 ***
## age          0.176999   0.002729  64.855  &lt; 2e-16 ***
## electric    -0.361758   0.068032  -5.317  1.1e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.471 on 4354 degrees of freedom
## Multiple R-squared:  0.5621, Adjusted R-squared:  0.5618 
## F-statistic:  1863 on 3 and 4354 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Our model returns a regression equation of:</p>
<p><span class="math display">\[\hat{children} = -2.071 - 0.079educ + 0.177age - 0.362electric\]</span></p>
<p><span class="math display">\[n = 4,358 \\
R^2 = 0.562\]</span></p>
</div>
<div id="q2.-interpret-hatbeta_0-hatbeta_education-hatbeta_age-and-hatbeta_electric" class="section level3" number="17.6.2">
<h3>
<span class="header-section-number">17.6.2</span> Q2. Interpret <span class="math inline">\(\hat{\beta}_0\)</span>, <span class="math inline">\(\hat{\beta}_{education}\)</span>, <span class="math inline">\(\hat{\beta}_{age}\)</span>, and <span class="math inline">\(\hat{\beta}_{electric}\)</span><a class="anchor" aria-label="anchor" href="#q2.-interpret-hatbeta_0-hatbeta_education-hatbeta_age-and-hatbeta_electric"><i class="fas fa-link"></i></a>
</h3>
<p><span class="math inline">\(\hat{\beta_0}\)</span>: This is the intercept, or the average predicted number of children when all three predictors are set to zero. It is -2.07 and is not theoretically meaningful (as you cannot have negative children).</p>
<p><span class="math inline">\(\hat{\beta}_{education}\)</span>: For every additional year of education a woman has, we would predict her to have, on average, -0.08 fewer children, holding all other things constant.</p>
<p><span class="math inline">\(\hat{\beta}_{age}\)</span>: For every additional year of age, we would predict a woman to have, on average, 0.18 more children, <em>ceteris paribus</em>.</p>
<p><span class="math inline">\(\hat{\beta}_{electric}\)</span>: Women with electricity have, on average, 0.36 fewer children than women without electricity, <em>ceteris paribus</em>.</p>
</div>
<div id="q3.-verify-that-sample-covariance-between-predicted-values-and-residuals-0." class="section level3" number="17.6.3">
<h3>
<span class="header-section-number">17.6.3</span> Q3. Verify that sample covariance between predicted values and residuals = 0.<a class="anchor" aria-label="anchor" href="#q3.-verify-that-sample-covariance-between-predicted-values-and-residuals-0."><i class="fas fa-link"></i></a>
</h3>
<p>There are two ways to do this. Mathematically, we can use the <code><a href="https://rdrr.io/r/stats/cor.html">cov()</a></code> command with the fitted values and residuals as inputs into the function.</p>
<div class="sourceCode" id="cb409"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">$</span><span class="va">fitted.values</span>, <span class="va">fmod1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -3.381377e-16</code></pre>
<div class="sourceCode" id="cb411"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -3.381377e-16</code></pre>
<p>While the covariance is not <em>exactly</em> 0, the number is so small, it is basically zero.</p>
<p>Note, finding the <em>correlation</em> between fitted values and residuals gets us to the same answer because a correlation coefficient is simply a mathematical transformation of the covariance that bounds the result to [-1,1].</p>
<div class="sourceCode" id="cb413"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">$</span><span class="va">fitted.values</span>, <span class="va">fmod1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##  Pearson's product-moment correlation
## 
## data:  fmod1$fitted.values and fmod1$residuals
## t = -9.1115e-15, df = 4356, p-value = 1
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.0296911  0.0296911
## sample estimates:
##           cor 
## -1.380524e-16</code></pre>
<p>You might remember from earlier stats classes that</p>
<p><span class="math display">\[correlation = \frac{covariance(x,y)}{\sigma_x \sigma_y}\]</span></p>
<p>So, the result of calculating the above equation manually should equal that of using the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> command</p>
<div class="sourceCode" id="cb415"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">$</span><span class="va">fitted.values</span>, <span class="va">fmod1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">$</span><span class="va">fitted.values</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -1.380524e-16</code></pre>
<p>We can also confirm that there is no relationship between the fitted values and residuals by plotting them.</p>
<p><em>(This is called a “residual versus fitted/predicted plot” and is a very useful tool in diagnosing models for potential problems like non-linearity, heteroskedasticity, and outliers. )</em></p>
<div class="sourceCode" id="cb417"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">fmod1</span><span class="op">$</span><span class="va">fitted.values</span>, y <span class="op">=</span> <span class="va">fmod1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Predicted number of children"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Residual"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"Predicted versus residual plot"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-142-1.png" width="672"></div>
</div>
<div id="q4.-verify-that-sample-covariance-between-education-and-residuals-0." class="section level3" number="17.6.4">
<h3>
<span class="header-section-number">17.6.4</span> Q4. Verify that sample covariance between education and residuals = 0.<a class="anchor" aria-label="anchor" href="#q4.-verify-that-sample-covariance-between-education-and-residuals-0."><i class="fas fa-link"></i></a>
</h3>
<p>We’ll do the same here as we did with the fitted versus residuals. First, we’ll use <code>R</code> to calculate the covariance.</p>
<div class="sourceCode" id="cb419"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cov</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">educ</span>, <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">fmod1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1.216786e-15</code></pre>
<p>As with before, this number is not <em>exactly</em> zero, but it is basically zero.</p>
<p>We can confirm this with visual inspection.</p>
<div class="sourceCode" id="cb421"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">dat</span><span class="op">$</span><span class="va">educ</span>, y <span class="op">=</span> <span class="va">fmod1</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Education"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Residual"</span>,</span>
<span>       title <span class="op">=</span> <span class="st">"Education versus residual plot"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-144-1.png" width="672"></div>
</div>
<div id="q5.-re-estimate-the-regression-equation-of-the-number-of-children-on-education-age-of-the-mother-and-electricity-but-also-include-the-square-of-the-age-of-the-mother.-how-do-you-now-interpret-the-effect-of-age-on-the-number-of-children" class="section level3" number="17.6.5">
<h3>
<span class="header-section-number">17.6.5</span> Q5. Re-estimate the regression equation of the number of children on education, age of the mother, and electricity but also include the square of the age of the mother. How do you now interpret the effect of age on the number of children?<a class="anchor" aria-label="anchor" href="#q5.-re-estimate-the-regression-equation-of-the-number-of-children-on-education-age-of-the-mother-and-electricity-but-also-include-the-square-of-the-age-of-the-mother.-how-do-you-now-interpret-the-effect-of-age-on-the-number-of-children"><i class="fas fa-link"></i></a>
</h3>
<p>Our population model is:</p>
<p><span class="math display">\[children = \beta_0 + \beta_1educ + \beta_2age + \beta_3age^2 + \beta_4electric + u\]</span></p>
<p>To include <span class="math inline">\(age^2\)</span> in the model, we can enclose it in parentheses and preface it with a capital “I” (i.e. <code>I(age^2)</code>). This tells the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> command to calculate whatever is inside <code><a href="https://rdrr.io/r/base/AsIs.html">I()</a></code>.</p>
<div class="sourceCode" id="cb423"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fmod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">children</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">age</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="va">electric</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fmod2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = children ~ educ + age + I(age^2) + electric, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.8576 -0.7153 -0.0005  0.7186  7.4868 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4.2475679  0.2406003 -17.654  &lt; 2e-16 ***
## educ        -0.0788944  0.0062513 -12.620  &lt; 2e-16 ***
## age          0.3370397  0.0165166  20.406  &lt; 2e-16 ***
## I(age^2)    -0.0026696  0.0002718  -9.822  &lt; 2e-16 ***
## electric    -0.3777901  0.0673176  -5.612 2.12e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.455 on 4353 degrees of freedom
## Multiple R-squared:  0.5716, Adjusted R-squared:  0.5712 
## F-statistic:  1452 on 4 and 4353 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Our model returns a regression equation of:</p>
<p><span class="math display">\[\hat{children} = -4.248 - 0.079educ + 0.337age - 0.0027age^2 - 0.362electric\]</span>
<span class="math display">\[n = 4,358 \\
R^2 = 0.572\]</span></p>
<p>Adding the quadratic (i.e. squared) term for age to the model returns a positive coefficient for <span class="math inline">\(age\)</span> and a negative coefficient for <span class="math inline">\(age^2\)</span>. This means that there is a positive relationship between age and the predicted number of children up until a point, and then the relationship becomes negative.</p>
<p>You can check this result by using a graphing calculator app like Desmos (<a href="https://www.desmos.com/calculator" class="uri">https://www.desmos.com/calculator</a>) and entering a function that only includes the terms for <span class="math inline">\(age\)</span> and <span class="math inline">\(age^2\)</span> (i.e. you would enter <span class="math inline">\(y = 0.337x - 0.0027x^2\)</span> into the app).</p>
<hr>
<p>Using the ‘wage1’ datadest from ‘woolridge’ on US workers in 1976…</p>
</div>
<div id="q6.-estimate-the-regression-equation-of-the-hourly-wage-wage-in-dollars-on-education-educ-and-experience-exper." class="section level3" number="17.6.6">
<h3>
<span class="header-section-number">17.6.6</span> Q6. Estimate the regression equation of the hourly wage (<span class="math inline">\(wage\)</span>) in dollars on education (<span class="math inline">\(educ\)</span>) and experience (<span class="math inline">\(exper\)</span>).<a class="anchor" aria-label="anchor" href="#q6.-estimate-the-regression-equation-of-the-hourly-wage-wage-in-dollars-on-education-educ-and-experience-exper."><i class="fas fa-link"></i></a>
</h3>
<p>Our population model is:</p>
<p><span class="math display">\[wage = \beta_0 + \beta_1educ + \beta_2exper + u\]</span></p>
<div class="sourceCode" id="cb425"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://justinmshea.github.io/wooldridge/">wooldridge</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"wage1"</span><span class="op">)</span></span>
<span><span class="va">wage_mod1</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span>, data<span class="op">=</span><span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wage_mod1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ educ + exper, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5532 -1.9801 -0.7071  1.2030 15.8370 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.39054    0.76657  -4.423 1.18e-05 ***
## educ         0.64427    0.05381  11.974  &lt; 2e-16 ***
## exper        0.07010    0.01098   6.385 3.78e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.257 on 523 degrees of freedom
## Multiple R-squared:  0.2252, Adjusted R-squared:  0.2222 
## F-statistic: 75.99 on 2 and 523 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Our model returns a regression equation of:</p>
<p><span class="math display">\[\hat{wage} = -3.391 - 0.644educ + 0.070exper\]</span>
<span class="math display">\[n = 526 \\
R^2 = 0.225\]</span></p>
<p>The terms are:</p>
<ul>
<li>
<span class="math inline">\(\hat{\beta}_{0}\)</span> : This is the intercept, or the predicted wage when all education and experience are both zero. three predictors are set to zero. It is -3.39 and is not theoretically meaningful (as one does not typically pay to work).</li>
<li>
<span class="math inline">\(\hat{\beta}_{educ}\)</span> : For every additional year of education a worker has, we would predict them to make, on average, an additional $0.64 per hour, <em>ceteris paribus</em>.</li>
<li>
<span class="math inline">\(\hat{\beta}_{exper}\)</span> : For every additional year of experience a worker has, we would predict them to make, on average, an additional $0.07 per hour, <em>ceteris paribus</em>.</li>
</ul>
</div>
<div id="q7.-how-do-the-coefficients-change-when-the-units-of-wages-are-in-cents-instead-of-dollars" class="section level3" number="17.6.7">
<h3>
<span class="header-section-number">17.6.7</span> Q7. How do the coefficients change when the units of wages are in cents instead of dollars?<a class="anchor" aria-label="anchor" href="#q7.-how-do-the-coefficients-change-when-the-units-of-wages-are-in-cents-instead-of-dollars"><i class="fas fa-link"></i></a>
</h3>
<p>The coefficients would all be multiplied by 100 (i.e. <span class="math inline">\(Intercept = -339.05\)</span>, <span class="math inline">\(educ = 64.43\)</span>, <span class="math inline">\(exper = 7.01\)</span>). This is because there are 100 cents in every dollar, so multiplying the left-hand side of the regression equation (i.e. the side containing <span class="math inline">\(\hat{wage}\)</span>) would require use to multiply the <em>entire</em> right hand side of the equation by 100 (i.e. the side that contains the terms <span class="math inline">\(\hat{\beta_0}\)</span>, <span class="math inline">\(\hat{\beta_{educ}}\)</span>, <span class="math inline">\(\hat{\beta_{exper}}\)</span>. This is equivalent to multiplying every single term on the right-hand side by 100 (i.e. factoring in the 100).</p>
<p><span class="math display">\[\begin{aligned}
\hat{wage_{dollars}} &amp;= -3.391 - 0.644educ + 0.070exper \\
\hat{wage_{cents}} &amp;= \hat{wage_{dollars}} \times 100 \\
100 \times \hat{wage_{dollars}} &amp;= [-3.391 - 0.644educ + 0.070exper] \times 100 \\
100 \times \hat{wage_{dollars}} &amp;= [-3.391 \times 100] - [0.644educ \times 100] + [0.070exper \times 100]  \\
\hat{wage_{cents}} &amp;= -339.1 - 64.4educ + 7.0exper \\
\end{aligned}\]</span></p>
<p>To confirm, let’s convert the <span class="math inline">\(wage\)</span> variable to cents and run the model again.</p>
<div class="sourceCode" id="cb427"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">wage_mod1a</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">wage</span><span class="op">*</span><span class="fl">100</span><span class="op">)</span> <span class="op">~</span> <span class="va">educ</span> <span class="op">+</span> <span class="va">exper</span>, data<span class="op">=</span><span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wage_mod1a</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = I(wage * 100) ~ educ + exper, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -555.32 -198.01  -70.71  120.30 1583.70 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -339.054     76.657  -4.423 1.18e-05 ***
## educ          64.427      5.381  11.974  &lt; 2e-16 ***
## exper          7.010      1.098   6.385 3.78e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 325.7 on 523 degrees of freedom
## Multiple R-squared:  0.2252, Adjusted R-squared:  0.2222 
## F-statistic: 75.99 on 2 and 523 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="q8.-compare-the-estimated-coefficient-for-education-to-the-one-obtained-by-regressing-only-the-hourly-wage-on-educaiton.-interpret." class="section level3" number="17.6.8">
<h3>
<span class="header-section-number">17.6.8</span> Q8. Compare the estimated coefficient for education to the one obtained by regressing only the hourly wage on educaiton. Interpret.<a class="anchor" aria-label="anchor" href="#q8.-compare-the-estimated-coefficient-for-education-to-the-one-obtained-by-regressing-only-the-hourly-wage-on-educaiton.-interpret."><i class="fas fa-link"></i></a>
</h3>
<p>This population model is:</p>
<p><span class="math display">\[wage = \beta_0 + \beta_1educ + u\]</span></p>
<div class="sourceCode" id="cb429"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">wage_mod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">wage</span> <span class="op">~</span> <span class="va">educ</span>, data<span class="op">=</span><span class="va">wage1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">wage_mod2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wage ~ educ, data = wage1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.3396 -2.1501 -0.9674  1.1921 16.6085 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.90485    0.68497  -1.321    0.187    
## educ         0.54136    0.05325  10.167   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.378 on 524 degrees of freedom
## Multiple R-squared:  0.1648, Adjusted R-squared:  0.1632 
## F-statistic: 103.4 on 1 and 524 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>It returns a regression equation of:</p>
<p><span class="math display">\[\hat{wage} = -0.905 - 0.541educ\]</span>
<span class="math display">\[n = 526 \\
R^2 = 0.165\]</span></p>
<p>In a simple bivariate model of <span class="math inline">\(wage\)</span> regressed on <span class="math inline">\(educ\)</span>, we get a coefficient of <span class="math inline">\(\hat{\beta}_{educ} = 0.541\)</span>. This is lower than the coefficient from the multiple regression model, where the effect of age was <span class="math inline">\(\hat{\beta}_{educ} = 0.644\)</span>. This suggests the omitted variable bias from not accounting for experience attenuates the estimated relationship between age and experience.</p>
<p>This shows that omitted variable bias does not always result in the overestimation of coefficients, but can also cause them to be <em>underestimated</em>.</p>
<p>Looking at the scatterplot <span class="math inline">\(wage\)</span> versus <span class="math inline">\(educ\)</span>, colour-coded by <span class="math inline">\(exper\)</span> gives some hints as to why we see this pattern. In the lower left-hand corner (i.e. low education and low wage), we see the greatest concentration of high to very high experience (green to yellow) versus other parts of the map. These could be older folks with lower levels of (formal) education and work in lower-paying “lower-skill” jobs.</p>
<p>While we see a clump of points that have low levels of experience (purple) in the lower left-hand corner, most of the the purple point tend to be above the simple bivariate regression line, which means they are outperforming what we would expect what we would expect in the model that does not account of experience.</p>
<div class="sourceCode" id="cb431"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">wage1</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">wage</span>, y<span class="op">=</span><span class="va">educ</span>, color<span class="op">=</span><span class="va">exper</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>position<span class="op">=</span><span class="st">"jitter"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_color_viridis_c</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Education"</span>, </span>
<span>       y<span class="op">=</span><span class="st">"Wage"</span>,</span>
<span>       color<span class="op">=</span><span class="st">"Exper"</span>,</span>
<span>       title<span class="op">=</span><span class="st">"Wage by education"</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="inline-figure"><img src="main_files/figure-html/unnamed-chunk-149-1.png" width="672"></div>
<hr>
</div>
</div>
<div id="additional-practice-questions" class="section level2" number="17.7">
<h2>
<span class="header-section-number">17.7</span> Additional practice questions<a class="anchor" aria-label="anchor" href="#additional-practice-questions"><i class="fas fa-link"></i></a>
</h2>
<p>There’s an old saying (often attributed to Winston Churchill) that says, “If you are not a liberal when you are young, you have no heart. If you are not a conservative when you are old, you have no brain.” And, yet there have been activist left-wing groups comprised of seniors, like the Raging Grannies.</p>
<p>Using our sample CES dataset, explore the relationship between Canadians’ support for free market principles (<span class="math inline">\(marketlib\)</span>) and age (<span class="math inline">\(age\)</span>)? Is there is a relationship? If so, is it <em>linear</em>?</p>
<p>We’re going to run two regression models. Model 1 will regress <span class="math inline">\(marketlib\)</span> on <span class="math inline">\(age\)</span>, while controlling for <span class="math inline">\(gender\)</span>. Model 2 will be the same as Model 1, except it will also include the quadratic term for <span class="math inline">\(age\)</span> (i.e. <span class="math inline">\(age^2\)</span>).</p>
<div class="sourceCode" id="cb433"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span><span class="op">(</span><span class="st">"Sample_data/ces.rda"</span><span class="op">)</span></span></code></pre></div>
<p>Before we begin, it’s useful to look at the univariate distributions of out variables. Besides letting us know of missing values, it also helps with interpreting the substantive significance of any relationships we find.</p>
<div class="sourceCode" id="cb434"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">marketlib</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##    0.00    6.00    9.00    8.59   11.00   16.00   32684</code></pre>
<div class="sourceCode" id="cb436"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">marketlib</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 3.519915</code></pre>
<div class="sourceCode" id="cb438"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">age</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    18.0    35.0    49.0    48.7    62.0    99.0</code></pre>
<div class="sourceCode" id="cb440"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 16.60883</code></pre>
<div class="sourceCode" id="cb442"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">gender</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Man Woman  NA's 
## 15517 21928   288</code></pre>
<div class="sourceCode" id="cb444"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">ces</span><span class="op">$</span><span class="va">gender</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
##       Man     Woman 
## 0.4143944 0.5856056</code></pre>
<p>Market liberalism variable ranges from 0 to 16, with a mean of 8.59 (SD = 3.52). <em>(Note: this is a simple additive index, or summated rating scale, of four Likert-type items that has been commonly used in Canadian political science research.)</em></p>
<p>Age ranges from 18 to 99, with a mean of 49.0 (SD = 16.61).</p>
<p>Gender is categorical variable, with about 58.6% being women and 41.4% being men.</p>
<div id="for-both-model-1-and-model-2-write-the-equation-of-the-population-models." class="section level3" number="17.7.1">
<h3>
<span class="header-section-number">17.7.1</span> 1. For both Model 1 and Model 2, write the equation of the population models.<a class="anchor" aria-label="anchor" href="#for-both-model-1-and-model-2-write-the-equation-of-the-population-models."><i class="fas fa-link"></i></a>
</h3>
<p>Our population models are:</p>
<p><span class="math display">\[\begin{aligned}
marketlib &amp;= \beta_0 + \beta_1gender + \beta_2age + \mu &amp;&amp; \text{(Model 1)} \\
marketlib &amp;= \beta_0 + \beta_1gender + \beta_2age + \beta_3age^2 + \mu &amp;&amp; \text{(Model 2)} \\
\end{aligned}\]</span></p>
</div>
<div id="run-the-regressions-and-write-out-the-equations-for-the-estimated-regression-models." class="section level3" number="17.7.2">
<h3>
<span class="header-section-number">17.7.2</span> 2. Run the regressions and write out the equations for the estimated regression models.<a class="anchor" aria-label="anchor" href="#run-the-regressions-and-write-out-the-equations-for-the-estimated-regression-models."><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb446"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">marketmod1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">marketlib</span> <span class="op">~</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">age</span>, data <span class="op">=</span> <span class="va">ces</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">marketmod1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = marketlib ~ gender + age, data = ces)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.3775 -2.2386  0.2442  2.5586  8.2885 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  8.309741   0.195029  42.608  &lt; 2e-16 ***
## genderWoman -0.855020   0.099390  -8.603  &lt; 2e-16 ***
## age          0.013516   0.003192   4.234 2.34e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.474 on 5022 degrees of freedom
##   (32708 observations deleted due to missingness)
## Multiple R-squared:  0.02078,    Adjusted R-squared:  0.02039 
## F-statistic: 53.28 on 2 and 5022 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Our regression equation for Model 1 is:</p>
<p><span class="math display">\[\hat{marketlib} = 8.309 - 0.855gender + 0.014age\]</span>
<span class="math display">\[n = 5025 \\ R^2 = 0.021 \]</span></p>
<div class="sourceCode" id="cb448"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">marketmod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">marketlib</span> <span class="op">~</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">age</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">ces</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">marketmod2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = marketlib ~ gender + age + I(age^2), data = ces)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.2733 -2.2700  0.4905  2.5909  8.9988 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.2610833  0.5002976  12.515  &lt; 2e-16 ***
## genderWoman -0.8560525  0.0992055  -8.629  &lt; 2e-16 ***
## age          0.0996610  0.0196397   5.074 4.03e-07 ***
## I(age^2)    -0.0008238  0.0001853  -4.445 8.97e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.467 on 5021 degrees of freedom
##   (32708 observations deleted due to missingness)
## Multiple R-squared:  0.02461,    Adjusted R-squared:  0.02403 
## F-statistic: 42.24 on 3 and 5021 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Our regression equation for Model 2 is:</p>
<p><span class="math display">\[\hat{marketlib} = 6.261 - 0.856gender + 0.100age -0.000824age^2\]</span>
<span class="math display">\[n = 5025 \\ R^2 = 0.025 \]</span></p>
</div>
<div id="explain-what-the-coefficients-mean-in-both-models.-how-does-the-effect-of-age-differ-between-model-1-and-model-2" class="section level3" number="17.7.3">
<h3>
<span class="header-section-number">17.7.3</span> 3. Explain what the coefficients mean in both models. How does the effect of age differ between Model 1 and Model 2?<a class="anchor" aria-label="anchor" href="#explain-what-the-coefficients-mean-in-both-models.-how-does-the-effect-of-age-differ-between-model-1-and-model-2"><i class="fas fa-link"></i></a>
</h3>
<p>Model 1, our coefficients are:</p>
<ul>
<li>
<span class="math inline">\(\hat{\beta_0}\)</span>: This is the intercept, or the average predicted market liberalism score for men and those 0 years old. While the value is 7.966, this value is not theoretically meaningful.</li>
<li>
<span class="math inline">\(\hat{\beta}_{age}\)</span>: For every additional year of age, we would predict a Canadian, on average, to be 0.022 more supportive of free market principles, holding all other things constant. With continuous variables like age, it’s often useful to convert the units–for example, we could represent this same relationship by saying that, on average, every increase of 10 years in age is associated with an increase of 0.220 on the market liberalism scale. (This also makes theoretical sense for a variable like age where we wouldn’t really expect a huge change year-over-year, but we might expect that for a change over 10 years.)</li>
<li>
<span class="math inline">\(\hat{\beta}_{gender}\)</span>: <em>Ceteris paribus</em>, women score an average of 0.826 points lower than men on the market liberalism scale.</li>
</ul>
<p>Model 2, our coefficients are:</p>
<ul>
<li>
<span class="math inline">\(\hat{\beta_0}\)</span>: This is the intercept, or the average predicted market liberalism score for men and those 0 years old. While the value is 6.782, this value is not theoretically meaningful.</li>
<li>
<span class="math inline">\(\hat{\beta}_{age}\)</span> and <span class="math inline">\(\hat{\beta}_{age^2}\)</span>: To understand the effect of age, we cannot just look at the coefficients for <span class="math inline">\(age\)</span> and <span class="math inline">\(age^2\)</span> individually; we have to look at them together. So, the effect of age on market liberalism is <span class="math inline">\(0.77age -0.000569age^2\)</span>. This is <em>non-linear</em>, meaning the rate of change is not the same across all possible changes across values of age. It also might be <em>non-monotonic</em>, meaning it is positive for some changes across values fo age and negative for others. <em>(If you want to see how we could graph this—which you don’t have to know for Assignment #1—it’s after Q4.)</em>
</li>
<li>
<span class="math inline">\(\hat{\beta}_{gender}\)</span>: <em>Ceteris paribus</em>, women score an average of 0.827 points lower than men on the market liberalism scale.</li>
</ul>
</div>
<div id="which-of-the-models-better-explains-the-relationship-between-marketlib-and-age" class="section level3" number="17.7.4">
<h3>
<span class="header-section-number">17.7.4</span> 4. Which of the models better explains the relationship between <span class="math inline">\(marketlib\)</span> and <span class="math inline">\(age\)</span>?<a class="anchor" aria-label="anchor" href="#which-of-the-models-better-explains-the-relationship-between-marketlib-and-age"><i class="fas fa-link"></i></a>
</h3>
<p>The <span class="math inline">\(R^2\)</span> for Model 1 is 0.074 and for Model 2, it is 0.079. This suggests that Model 2 fits the data better than Model 1. There is a bit more to comparing model fit, and we’ll get to that in a few weeks time, but this is the starting point.</p>
<p>Also, empirical performance isn’t everything. Fortunately, there are also theoretical reasons to suspect that the effect of age might not be a clear-cut linear relationship suggested by the old adage. Older folks typically have lower levels of income and tend to rely upon the welfare state more than younger folks (on average, and all other things being equal). So, life-cycle effects might cause their interests to change, and by extension, their orientations on how society ought to be run.</p>
<p>There is also the issue that comparing across ages at one point in time cannot separate life-cycle effects from generational effects, which neither of these models would be able to disentangle.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="tutorial-6-regression-analysis-and-interpretation.html"><span class="header-section-number">16</span> Tutorial 6: Regression Analysis and Interpretation</a></div>
<div class="next"><a href="lecture-7-the-multiple-regression-model-ii.html"><span class="header-section-number">18</span> Lecture 7: The Multiple Regression Model II</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#lecture-6-exercises"><span class="header-section-number">17</span> Lecture 6 Exercises</a></li>
<li>
<a class="nav-link" href="#how-to-nicely-display-model-results"><span class="header-section-number">17.1</span> How to (nicely) display model results</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-boring-ugly-way-base-r"><span class="header-section-number">17.1.1</span> The boring, ugly way (Base R)</a></li>
<li><a class="nav-link" href="#stargazer"><span class="header-section-number">17.1.2</span> {stargazer}</a></li>
<li><a class="nav-link" href="#modelsummary"><span class="header-section-number">17.1.3</span> {modelsummary}</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#functional-form"><span class="header-section-number">17.2</span> Functional form</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#feelings-towards-the-lpc-quadratics"><span class="header-section-number">17.2.1</span> Feelings towards the LPC (quadratics)</a></li>
<li><a class="nav-link" href="#occupational-prestige-logarithms"><span class="header-section-number">17.2.2</span> Occupational prestige (logarithms)</a></li>
<li><a class="nav-link" href="#automobile-performance-logarithms"><span class="header-section-number">17.2.3</span> Automobile performance (logarithms)</a></li>
</ul>
</li>
<li><a class="nav-link" href="#practice-exercises-1"><span class="header-section-number">17.3</span> Practice exercises</a></li>
<li><a class="nav-link" href="#stop-4"><span class="header-section-number">17.4</span> STOP!!</a></li>
<li><a class="nav-link" href="#continue-4"><span class="header-section-number">17.5</span> Continue</a></li>
<li>
<a class="nav-link" href="#lecture-exercises"><span class="header-section-number">17.6</span> Lecture exercises</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#q1.-estimate-the-regression-equation-of-the-number-of-children-on-education-age-of-the-mother-and-electricity."><span class="header-section-number">17.6.1</span> Q1. Estimate the regression equation of the number of children on education, age of the mother, and electricity.</a></li>
<li><a class="nav-link" href="#q2.-interpret-hatbeta_0-hatbeta_education-hatbeta_age-and-hatbeta_electric"><span class="header-section-number">17.6.2</span> Q2. Interpret \(\hat{\beta}_0\), \(\hat{\beta}_{education}\), \(\hat{\beta}_{age}\), and \(\hat{\beta}_{electric}\)</a></li>
<li><a class="nav-link" href="#q3.-verify-that-sample-covariance-between-predicted-values-and-residuals-0."><span class="header-section-number">17.6.3</span> Q3. Verify that sample covariance between predicted values and residuals = 0.</a></li>
<li><a class="nav-link" href="#q4.-verify-that-sample-covariance-between-education-and-residuals-0."><span class="header-section-number">17.6.4</span> Q4. Verify that sample covariance between education and residuals = 0.</a></li>
<li><a class="nav-link" href="#q5.-re-estimate-the-regression-equation-of-the-number-of-children-on-education-age-of-the-mother-and-electricity-but-also-include-the-square-of-the-age-of-the-mother.-how-do-you-now-interpret-the-effect-of-age-on-the-number-of-children"><span class="header-section-number">17.6.5</span> Q5. Re-estimate the regression equation of the number of children on education, age of the mother, and electricity but also include the square of the age of the mother. How do you now interpret the effect of age on the number of children?</a></li>
<li><a class="nav-link" href="#q6.-estimate-the-regression-equation-of-the-hourly-wage-wage-in-dollars-on-education-educ-and-experience-exper."><span class="header-section-number">17.6.6</span> Q6. Estimate the regression equation of the hourly wage (\(wage\)) in dollars on education (\(educ\)) and experience (\(exper\)).</a></li>
<li><a class="nav-link" href="#q7.-how-do-the-coefficients-change-when-the-units-of-wages-are-in-cents-instead-of-dollars"><span class="header-section-number">17.6.7</span> Q7. How do the coefficients change when the units of wages are in cents instead of dollars?</a></li>
<li><a class="nav-link" href="#q8.-compare-the-estimated-coefficient-for-education-to-the-one-obtained-by-regressing-only-the-hourly-wage-on-educaiton.-interpret."><span class="header-section-number">17.6.8</span> Q8. Compare the estimated coefficient for education to the one obtained by regressing only the hourly wage on educaiton. Interpret.</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#additional-practice-questions"><span class="header-section-number">17.7</span> Additional practice questions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#for-both-model-1-and-model-2-write-the-equation-of-the-population-models."><span class="header-section-number">17.7.1</span> 1. For both Model 1 and Model 2, write the equation of the population models.</a></li>
<li><a class="nav-link" href="#run-the-regressions-and-write-out-the-equations-for-the-estimated-regression-models."><span class="header-section-number">17.7.2</span> 2. Run the regressions and write out the equations for the estimated regression models.</a></li>
<li><a class="nav-link" href="#explain-what-the-coefficients-mean-in-both-models.-how-does-the-effect-of-age-differ-between-model-1-and-model-2"><span class="header-section-number">17.7.3</span> 3. Explain what the coefficients mean in both models. How does the effect of age differ between Model 1 and Model 2?</a></li>
<li><a class="nav-link" href="#which-of-the-models-better-explains-the-relationship-between-marketlib-and-age"><span class="header-section-number">17.7.4</span> 4. Which of the models better explains the relationship between \(marketlib\) and \(age\)?</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/svallejovera/regression_ci/blob/master/17-exercises6.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/svallejovera/regression_ci/edit/master/17-exercises6.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>PS9591: Regressions and Causal Inference</strong>" was written by Dr. Sebastián Vallejo Vera | Western University. It was last built on 2025-05-19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
